# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: do-something
    
  # Trigger when release created
  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build USD
      run: python build_scripts/build_usd.py --no-examples --no-usdview  --no-tutorials ../artifacts/usd
    
#    - name: Create Artifact
#      uses: actions/upload-artifact@v1 
#      with:
#          name: macOS
#          path: ../artifacts/usd
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ../artifacts/usd
        asset_name: macOS
        tag: latest
        overwrite: true
