# This is a basic workflow to help you get started with Actions

name: Release Build macOS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: do-something
    
  # Trigger when release created
  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build USD
      run: python3 build_scripts/build_usd.py --build-args Alembic,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" Blosc,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" Draco,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" Embree,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" HDF5,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" JPEG,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" MaterialX,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" OpenColorIO,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" OpenEXR,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" OpenImageIO,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" OpenSubdiv,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" OpenVDB,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" PNG,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" Ptex,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" TBB,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" TIFF,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" USD,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" boost,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" zlib,"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" --no-examples --no-usdview  --no-tutorials  --no-python --no-tools ../artifacts/usd
    
    - name: Archive the release
      run: |
            cd ../artifacts/usd
            echo "Create an archive containing the install files"
            tar --posix -zcf usd_macOS_amd64.tar.gz *
            echo "Done"
            cd ..
            mv usd/usd_macOS_amd64.tar.gz .
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ../artifacts/usd_macOS_amd64.tar.gz
        asset_name: usd_macOS_amd64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
