# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: do-something
    
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build USD
      run: python build_scripts/build_usd.py --no-examples --no-usdview  --no-tutorials ../install
      
    - name: Zip Artifact
      uses: montudor/action-zip@v0.1.0
      with:
          args: zip -qq -r ../macos.zip ../install/*
    
    - name: Create Artifact
      uses: actions/upload-artifact@v1 
      with:
          name: USD
          path: ../macos.zip
